# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
- group: "KV Secrets"
- name: erik
  value: $(DOCKER-SERVICE-CONN-ID)

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: export DOCKER_HOST=$(DOCKER-SERVICE-CONN-ID)
  displayName: 'Run a one-line script'

- task: Docker@2
  inputs:
    containerRegistry: $DOCKER_HOST
    command: 'login'


- script: |
    printenv
    test=$(DOCKER-SERVICE-CONN-ID)
    echo " length: ${#erik}"
    echo " length: ${#test}"
  displayName: 'Run a multi-line script'
