# This file contains the variables and jobs for the dev stage

.dev-vars: &dev-vars
  ARM_CLIENT_ID: $DEV_ARM_CLIENT_ID
  ARM_CLIENT_SECRET: $DEV_ARM_CLIENT_SECRET
  AZURE_STORAGE_ACCOUNT_NAME: $DEV_AZURE_STORAGE_ACCOUNT_NAME
  AZURE_STORAGE_ACCOUNT_CONTAINER: $DEV_AZURE_STORAGE_ACCOUNT_CONTAINER
  AZURE_STORAGE_ACCOUNT_SUBSCRIPTION: $DEV_AZURE_STORAGE_ACCOUNT_SUBSCRIPTION
  VAR_FILE_NAME: 'DEV_TF_VARS'
  ENVIRONMENT: 'dev'

DevBuild:
  extends: .build
  stage: Dev-Build
  variables:
    <<: *dev-vars
  only:
    - master
    - merge_requests
    - web

DevRelease:
  extends: .release
  stage: Dev-Release
  variables:
    <<: *dev-vars
  needs:
    - job: DevBuild
      artifacts: true
  when: on_success
  only:
    - master
    - merge_requests
    - web