trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - /devops/providers/azure-devops/templates/infrastructure/*
    exclude:
    - /**/*.md

pr:
  branches:
    include:
    - '*'
  paths:
    include:
    - /devops/providers/azure-devops/templates/infrastructure/*
    exclude:
    - /**/*.md

variables:
- group: 'Infrastructure Pipeline Variables'

stages:
- template: azure-pipeline-cicd-compose.yml
  parameters:
    environments:
    - name: 'devint'
      enablePrIsolation: true
      resourceNameIsolationLevel: 8
    - name: 'qa'
      enablePrIsolation: false
      resourceNameIsolationLevel: 0

    configurationMatrix:
    - jobName: template_deployment
      terraformTemplatePath: '$(TF_DEPLOYMENT_TEMPLATE_ROOT)'
      deploymentTimeoutInMinutes: 120