parameters:
  environments: []
  configurationMatrix: []

stages:

- stage: PublishBuildArtifact
  jobs:
  - template: azure-pipeline-initial-artifact.yml

- ${{ each environment in parameters.environments }}:
  - stage: ${{ environment.name }}_Build
    jobs:
    - template: azure-pipeline-build-stage.yml
      parameters:
        environment: ${{ environment.name }}
        enablePrIsolation: ${{ environment.enablePrIsolation }}
        resourceNameIsolationLevel: ${{ environment.resourceNameIsolationLevel }}
        configurationMatrix: ${{ parameters.configurationMatrix }}

  - stage: ${{ environment.name }}_Release
    jobs:
    - template: azure-pipeline-release-stage.yml
      parameters:
        environment: ${{ environment.name }}
        enablePrIsolation: ${{ environment.enablePrIsolation }}
        resourceNameIsolationLevel: ${{ environment.resourceNameIsolationLevel }}
        configurationMatrix: ${{ parameters.configurationMatrix }}
