parameters:
  environments: []
  configurationMatrix: []

stages:

- stage: PublishBuildArtifact
  jobs:
  - job: Publish
    displayName: Publish App Repo Infrastructure Files
    steps:
    - task: CopyFiles@2
      displayName: Copy Terraform Files to Artifact Directory
      inputs:
        contents: 'infra/**'
        sourceFolder: $(Build.SourcesDirectory)
        targetFolder: $(Build.ArtifactStagingDirectory)
    - task: PublishBuildArtifacts@1
      displayName: Publish Artifact
      inputs:
        parallel: true
        parallelCount: 8
        artifactName: '$(BUILD_ARTIFACT_NAME)'
        pathToPublish: $(Build.ArtifactStagingDirectory)

- ${{ each environment in parameters.environments }}:
  - stage: ${{ environment }}_Build
    jobs:
    - template: azure-pipeline-build-stage.yml
      parameters:
        environment: ${{ environment }}
        configurationMatrix: ${{ parameters.configurationMatrix }}
        skipTests: true
        forceRun: true

  - stage: ${{ environment }}_Release
    jobs:
    - template: azure-pipeline-release-stage.yml
      parameters:
        environment: ${{ environment }}
        configurationMatrix: ${{ parameters.configurationMatrix }}
        skipTests: true
        forceRun: true
