trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - /infra/modules/*
    - /infra/templates/*
    exclude:
    - devops/*
    - design-reference/*
    - README.md
pr:
  autoCancel: false
  branches:
    include:
    - master
  paths:
    include:
    - /infra/modules/*
    - /infra/templates/*
    - /tests/*
    exclude:
    - devops/*
    - design-reference/*
    - README.md

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  GOBIN:  '$(GOPATH)/bin' # Go binaries path
  GOROOT: '/usr/local/go1.11' # Go installation path
  GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
  modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)' # Path to the module's code

steps:
- script: |
    mkdir -p '$(GOBIN)'
    mkdir -p '$(GOPATH)/pkg'
    mkdir -p '$(modulePath)'
    shopt -s extglob
    shopt -s dotglob
    mv !(gopath) '$(modulePath)'
    echo '##vso[task.prependpath]$(GOBIN)'
    echo '##vso[task.prependpath]$(GOROOT)/bin'
  displayName: 'Set up Go workspace'
